kind: pipeline
name: default
steps:
  - name: ganache
    image: trufflesuite/ganache-cli:v6.4.3
    detach: true

  - name: core
    image: enigmampc/enigma-core:0.0.8
    depends_on: [clone]
    privileged: true
    commands:
      - LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service
      - . /opt/sgxsdk/environment && . /root/.cargo/env
      - cd enigma-core && RUSTFLAGS=-Awarnings make DEBUG=1
      - cd app && RUSTFLAGS=-Awarnings cargo test
    volumes:
      - name: isgx
        path: /dev/isgx

  - name: principal
    image: enigmampc/enigma-core:0.0.8
    depends_on: [clone]
    privileged: true
    commands:
      - LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service
      - . /opt/sgxsdk/environment && . /root/.cargo/env
      - cd enigma-principal && RUSTFLAGS=-Awarnings make DEBUG=1
      - export NODE_URL="http://ganache:8545"
      - cd app && RUSTFLAGS=-Awarnings cargo test
    volumes:
      - name: isgx
        path: /dev/isgx

  - name: tools_u
    image: enigmampc/enigma-core:0.0.8
    depends_on: [clone]
    commands:
      - . /root/.cargo/env
      - export NODE_URL="http://ganache:8545"
      - cd enigma-tools-u
      - RUSTFLAGS=-Awarnings cargo test

  - name: enigma_crypto
    image: enigmampc/enigma-core:0.0.8
    depends_on: [clone]
    commands:
      - . /root/.cargo/env
      - cd enigma-crypto
      - RUSTFLAGS=-Awarnings cargo test
      - RUSTFLAGS=-Awarnings cargo build --no-default-features --features=sgx

  - name: tools_m
    image: enigmampc/enigma-core:0.0.8
    depends_on: [clone]
    commands:
      - . /root/.cargo/env
      - cd enigma-tools-m
      - RUSTFLAGS=-Awarnings cargo test
      - RUSTFLAGS=-Awarnings cargo build --no-default-features --features=sgx

  - name: enigma_types
    image: enigmampc/enigma-core:0.0.8
    depends_on: [clone]
    commands:
      - . /root/.cargo/env
      - cd enigma-types
      - RUSTFLAGS=-Awarnings cargo test
      - RUSTFLAGS=-Awarnings cargo build --no-default-features
      - RUSTFLAGS=-Awarnings cargo build --no-default-features --features=sgx
      - RUSTFLAGS=-Awarnings cargo build --no-default-features --features=alloc

  - name: integration
    image: enigmampc/docker-client
    depends_on:
      - core
      - principal
    commands:
      - git clone https://github.com/enigmampc/discovery-docker-network.git
      - cd discovery-docker-network && cp .env-template .env
      - sed -i "s/COMPOSE_PROJECT_NAME=.*/COMPOSE_PROJECT_NAME=enigma_${DRONE_BUILD_NUMBER}/" .env
      - if [[ ${DRONE_BRANCH} == "master" ]]; then export TAG=latest; else export TAG=develop; fi
      - if [[ $TAG == "develop" ]]; then sed -i "s/DOCKER_TAG=latest/DOCKER_TAG=develop/" .env; fi
      - docker-compose pull
      - |
        cd enigma-core &&
        docker build --build-arg GIT_BRANCH_CORE=$DRONE_BRANCH --build-arg SGX_MODE=HW -t enigmampc/enigma_core_hw:$TAG --no-cache . &&
        docker build -f Dockerfile.km --build-arg GIT_BRANCH_CORE=$DRONE_BRANCH --build-arg SGX_MODE=HW -t enigmampc/enigma_km_hw:$TAG --no-cache . &&
        cd ..
      - docker-compose -f docker-compose.yml -f docker-compose.hw.yml -f docker-compose.test.yml up --exit-code-from client
    privileged: true
    volumes:
      - name: sock
        path: /var/run/docker.sock

  - name: deploy
    image: enigmampc/docker-client
    depends_on:
      - integration
    when:
      branch:
        - develop
        - master
    environment:
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
    commands:
      - cd discovery-docker-network/enigma-core
      - sed -i "s/-vv/-v/" start_core.bash && sed -i "s/-vv/-v/" start_km.bash
      - echo $PASSWORD | docker login -u $USERNAME --password-stdin
      - if [[ ${DRONE_BRANCH} == "master" ]]; then export TAG=latest; else export TAG=develop; fi
      - docker build --build-arg GIT_BRANCH_CORE=$DRONE_BRANCH --build-arg SGX_MODE=HW -t enigmampc/enigma_core_hw:$TAG --no-cache .
      - docker push enigmampc/enigma_core_hw:$TAG
      - docker build -f Dockerfile.km --build-arg GIT_BRANCH_CORE=$DRONE_BRANCH --build-arg SGX_MODE=HW -t enigmampc/enigma_km_hw:$TAG --no-cache .
      - docker push enigmampc/enigma_km_hw:$TAG
      - docker build --build-arg GIT_BRANCH_CORE=$DRONE_BRANCH --build-arg SGX_MODE=SW -t enigmampc/enigma_core_sw:$TAG --no-cache .
      - docker push enigmampc/enigma_core_sw:$TAG
      - docker build -f Dockerfile.km --build-arg GIT_BRANCH_CORE=$DRONE_BRANCH --build-arg SGX_MODE=SW -t enigmampc/enigma_km_sw:$TAG --no-cache .
      - docker push enigmampc/enigma_km_sw:$TAG
    privileged: true
    volumes:
      - name: sock
        path: /var/run/docker.sock

volumes:
  - name: isgx
    host:
      path: /dev/isgx
  - name: sock
    host:
      path: /var/run/docker.sock
