unstable_features = true
max_width = 120
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
fn_args_density = "Compressed"
fn_single_line = true
imports_indent = "Visual"
indent_style = "Visual"
where_single_line = true
edition = "2018"