language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
env: 
  - TEST_DIR=app
  - TEST_DIR=enclave
script:
  - cd $TEST_DIR && cargo build --verbose --all
  - cd $TEST_DIR && cargo test --verbose --all