[package]
name = "enigma-principal-app"
version = "0.1.3"
authors = ["Enigma <support@enigma.co>"]
build = "build.rs"

[dependencies]
enigma-tools-u = {path = "../../enigma-tools-u"}

ethabi = "6.0.1"
base64 = "0.10.0"
libc = "0.2.41"
etcommon-rlp = {git = "https://github.com/ETCDEVTeam/etcommon-rs.git"}
etcommon-trie = {git = "https://github.com/ETCDEVTeam/etcommon-rs.git"}
etcommon-block-core = {git = "https://github.com/ETCDEVTeam/etcommon-rs.git"}
etcommon-block = {git = "https://github.com/ETCDEVTeam/etcommon-rs.git"}
etcommon-bigint = {git = "https://github.com/ETCDEVTeam/etcommon-rs.git"}
etcommon-bloom = {git = "https://github.com/ETCDEVTeam/etcommon-rs.git"}
failure = "=0.1.1"
failure_derive="=0.1.1"
rustc-hex = "1.0.0"
tokio-core = "0.1.17"
serde_json = "1.0"
serde = "1.0.66"
serde_derive = "1.0.70"
structopt = "0.2.10"
url = "1.7.1"
tiny-keccak = "1.4.2"
colour = "0.2.1"
dirs = "1.0"
#web3 = { path = "../../../rust-web3" } #TODO: Change after a new version is released.
web3 = { git = "https://github.com/tomusdrw/rust-web3.git" } #TODO: Change after a new version is released.

jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-minihttp-server = { git = "https://github.com/paritytech/jsonrpc" }
rocksdb = { git = "https://github.com/elichai/rust-rocksdb.git" } # This is temporary, until PR is merged

sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
