[package]
name = "eng_wasm_dispatch"
version = "0.1.0"

[dependencies]
eng_wasm = {path = "../../eng_wasm"}
proc-macro2 = "0.4"
quote = "0.6.8"
syn = { version = "0.15.12", features = ["full", "extra-traits"] }

[lib]
proc-macro = true
