[package]
name = "eng-wasm"
version = "0.1.2"
authors = ["moria <moria@enigma.co>"]
license = "AGPL-3.0"
description = "Enigma library for creating Secret Contracts"
keywords = ["wasm", "webassembly", "blockchain", "sgx", "enigma"]
exclude = ["derive/*"]
categories = ["wasm"]

[dependencies]
serde_json = "1.0"
serde = "1.0"
eng-pwasm-abi = "0.2.1"
failure_derive = "0.1.5"
failure = { version = "0.1.5", default-features = false, features = ["derive"] }
syn = { version = "0.15", features = ["full", "extra-traits"] }
tiny-keccak = "1.4"
ethabi = "6.1.0"
byteorder = "1.3"