[package]
name = "enigma-runtime-t"
version = "0.1.0"
authors = ["Elichai Turkel <elichai@enigma.co>"]

[dependencies]
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.0" }
serde_json = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.0" }
serde = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.0" }

rmp-serde = { git = "https://github.com/enigmampc/msgpack-rust.git", rev = "sgx"}
enigma-tools-t = { path = "../enigma-tools-t" }
json-patch = { git = "https://github.com/enigmampc/json-patch.git", rev = "sgx-0.2.2" }