[package]
name = "app"
version = "0.9.8"
authors = ["enigma <support@enigma.co>"]
build = "build.rs"

[dependencies]
sgx_types = { path = "/root/sgx/sgx_types" }
sgx_urts = { path = "/root/sgx/sgx_urts" }
base64 = "0.9.1"
libc = "0.2.41"