[package]
name = "enigma-tools-u"
version = "0.1.0"
authors = ["Isan-Rivkin <isanrivkin@gmail.com>"]
description = "Tools used by the untrusted part of the Enigma core and Principal node."

[dependencies]
serde_json = "1.0"
serde = "1.0.66"
serde_derive = "1.0.66"
failure = "0.1.1"
httparse = "=1.2.5"
reqwest = "0.8.6"
etcommon-rlp = {rev = "0.2.3", default-features = false}
# web3 utils 
web3 = { git = 'https://github.com/tomusdrw/rust-web3.git' }
libc = "0.2.41"
rustc-hex = "1.0.0"
tiny-keccak = "1.4.2"
base64 = "0.9.1"
# enigma contract 
[dependencies.sgx_types]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"
# esgx
[dependencies.sgx_urts]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

