[package]
name = "enigma-tools-u"
version = "0.1.3"
authors = ["Isan-Rivkin <isan@enigma.co>"]
description = "Tools used by the untrusted part of the Enigma core and Principal node."
build = "build.rs"

[dependencies]
enigma-crypto = { path = "../enigma-crypto" }

serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
failure = "0.1.3"
failure_derive = "0.1.3"
reqwest = "0.9.5"
etcommon-rlp = "0.2.4"
base64 = "0.10.0"
openssl = "0.10.16"
rustc-hex = "1.0.0" # 2.0.1?
web3 = { git = "https://github.com/tomusdrw/rust-web3.git" } #TODO: Change after a new version is released.
libc = "0.2.45"
tiny-keccak = "1.4.2"
ethabi = "6.1.0"
log = "0.4"
log-derive = "0.2.0"

sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
